### ISSUE TITLE
Valid instruction size suffixes are rejected in .assume adl=0 code

### ISSUE THREAD

**Issue by tomm** [envenomator/agon-ez80asm#29]
agon-ez80asm rejects push.lil and various other suffixed instructions when in .assume adl=0. It says:

"mything.asm" - line 34 - Suffix not matching mnemonic / ADL mode

I'm pretty sure it should be permitted. BBC BASIC uses them extensively in its init.asm

**Comment by envenomator** [comment]
This is similar to issue #18. I still haven't received an official answer from Zilog/Littlefuse yet.

The PUSH opcodes are unambiguous, i.e. fixed in length without an immediate depending on ADL mode. Therefore, for ADL=0 the .L part (Data block Long) is valid for mixed mode applications, while the .IL (Instruction Long) makes no sense with fixed length instructions. The PUSH instructions imply the assembler expand the full suffix to .LIS in the datasheet for ADL=0. 
However, the datasheet mentions (page 19) - "If the length of the instruction is unambiguous, the .IS and .IL suffixes yield no effect." So in other words, while the expansion of a suffix may be applied incorrectly with fixed-length instructions, they aren't <illegal> because the CPU ignores the .Ix part of the suffix.

It also explains why the ZDS assembler itself outputs such incorrectly applied suffixes by the user.

I'll fix both this issue and issue #18 in the next update.

**Comment by envenomator** [comment]
Fixed in v0.98
