### ISSUE TITLE
Support code inlining through colon

### ISSUE THREAD

**Issue by nihirash** [envenomator/agon-ez80asm#30]
Hello! Thank you for your great work!

 I've used sjasmplus for a long time and it supported code inlining through colon. 

What I mean?
```
   LD a, b : or c : jr nz, @label
```

This code should be equal to

```
  ld a, b
  or c 
  jr nz, @label
```

 It allows "pack" code to logical blocks and make it more compact and sometimes more readable. I know that many assembler don't support same behaviour but if it's possible - it will be great, especially for larger projects.  

If colon isn't usable - any other symbol will be acceptable too(for example `/`)

**Comment by envenomator** [comment]
Hi,

You're welcome! It is a fun project to work on.

This enhancement request is actually a little tricky to implement, which I believe might also be the reason why other assemblers don't implement it at all.
By default each line is parsed from the input file using the end-of-line character(s). To avoid needing to write an additional tokenizer for single lines / re-use the existing tokenizer, I'd need to break up a single line in multiple lines, by using an additional end-of-line equivalent character. That part is easy, but the consequence would be that this character would also need escaping during normal use, i.e. in strings and such. It would also impact the code for counting lines in files, which propagates all through the listing etc.
The colon would be problematic because of it's use as label ending character, as would most other characters used in strings and values. And I'd hate to insert escape-handling code in the io_gets method, because that would impact performance during most line reads. Not much impact on a modern PC, but on the Agon every cycle counts.

I'll have to think on this a little

**Comment by envenomator** [comment]
The code necessary to implement this (I have something working), becomes very ugly very quickly. Because whatever code we'd use for delimiter, I'd still need to track the escaping of it in a line and also if it's used in a string or literal. That's doable, but it slows the parser down. More importantly, it creates havoc in error feedback to the user when using that same delimiter incorrectly in an actual string or literal, because the line/token has already broken and there is no way to differentiate without adding <additional> code to track that state.
It would have been nice, but due to this reason I'll not be implementing this.
