### ISSUE TITLE
incbin lost last byte in binary file

### ISSUE THREAD

**Issue by nihirash** [envenomator/agon-ez80asm#6]
When I've included binary(for example bitmap), I've got not full file included(last byte was lost). 

Example:
[fail.zip](https://github.com/envenomator/agon-ez80asm/files/11168235/fail.zip)

It currently works cause I've put lost byte by hands. 
Check main.asm - I've put comments here.

**Comment by envenomator** [comment]
Thnx, i'll check this out.

**Comment by nihirash** [comment]
Looks like I was wrong and everything working fine. 

Please check it but sounds like false alert.

**Comment by envenomator** [comment]
No, you were right!
There is a very subtle difference in how FatFS does feof, versus how C/C++ does feof. The latter gives you 1 if you have read PAST the last character/byte in the file, not AT the last one as FatFS does. Because I've coded an abstraction layer to MOS filesystems calls to run my code in Linux for debugging, I need to handle the difference in feof in code now. Will fix this in the next update
